In [ ]:
#Prayan Piya
#2462985
#np03cs4a240098

Problem - 1: Array Creation:

In [1]:
#1
import numpy as np

arr = np.zeros((2,2))

In [2]:
#2
arr = np.ones((4,2))

In [3]:
#3
def fill_arr(r,c,value):
    return np.full((r,c),value)

fill_arr(4,2,5)

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [4]:
#4
def fill_zero_arr(arr):
    return np.zeros_like(arr)

arr1 = [[1,2],[3,4],[5,6]]
fill_zero_arr(arr1)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [5]:
#5
def fill_zero_arr(arr):
    return np.ones_like(arr)

arr1 = [[1,2],[3,4],[5,6]]
fill_zero_arr(arr1)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [6]:
#6
new_list = [1,2,3,4]
converted_array = np.array(new_list)

converted_array

array([1, 2, 3, 4])

Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [7]:
#1
values_array = np.arange(10,50)

values_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
#2
value_array = np.arange(0,9)
matrix = value_array.reshape(3,3)

matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
#3
identity_matrix = np.eye(3)

identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
#4
random_array = np.random.random(30)
mean = random_array.mean()

print("Array: \n", random_array)
print("Mean: ", mean.item())

Array: 
 [0.367004   0.58011844 0.80866407 0.58941136 0.24058865 0.13793553
 0.93375588 0.30794959 0.39390864 0.25553247 0.496641   0.64126211
 0.78366402 0.34459261 0.8736893  0.06107968 0.91587214 0.417158
 0.04408721 0.15697932 0.80990556 0.11246306 0.18640244 0.59560981
 0.11436902 0.05486262 0.52804664 0.80027116 0.56705745 0.5614747 ]
Mean:  0.45601188265456766


In [11]:
#5
array = np.random.random((10,10))
minimum = array.min()
maximum = array.max()

print("Array: \n", array)
print("Minimum value: ", minimum)
print("Maximum value: ", maximum)

Array: 
 [[0.09219788 0.77923397 0.50713981 0.09336898 0.11215678 0.71908607
  0.71197878 0.99453071 0.02147187 0.68430411]
 [0.41088643 0.33931273 0.71999014 0.74353743 0.56353426 0.63039818
  0.78178617 0.05782067 0.4397103  0.87144471]
 [0.26616797 0.44426906 0.32099055 0.16501617 0.69676708 0.10475465
  0.6037901  0.99191791 0.48741654 0.71518513]
 [0.75225842 0.60719267 0.39449998 0.76429068 0.72522691 0.29093591
  0.31451546 0.70436694 0.72073091 0.96994595]
 [0.009193   0.18837034 0.088882   0.65074708 0.49376057 0.56309496
  0.77618215 0.13714291 0.16839323 0.43918071]
 [0.40492821 0.5824508  0.97565875 0.02294305 0.3268879  0.60049087
  0.85572197 0.56888981 0.8182917  0.22940537]
 [0.38988517 0.43098395 0.30984695 0.48729454 0.24448573 0.02117251
  0.720897   0.2912978  0.17630036 0.99949807]
 [0.1439468  0.10603412 0.26539626 0.38876442 0.23111202 0.54323035
  0.90512347 0.54231005 0.88140677 0.45765328]
 [0.46935757 0.65730195 0.88019798 0.68473812 0.1567048  0.75725254
  0

In [39]:
#6
zero_array = np.zeros(10)
print("Array before changing the 5th element: ", zero_array)

zero_array[4] = 1
print("Array after changing the 5th element: ", zero_array)

Array before changing the 5th element:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array after changing the 5th element:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
#7
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]

print("Array reversed is: ", reversed_arr)

Array reversed is:  [0 4 0 0 2 1]


In [13]:
#8
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
#9
array = np.zeros((8,8))
array[1::2, ::2] = 1
array[::2, 1::2] = 1

array

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [15]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [16]:
#1
print(x+y)

[[ 6  8]
 [10 13]]


In [17]:
#2
print(x-y)

[[-4 -4]
 [-4 -3]]


In [18]:
#3
print(x*6)

[[ 6 12]
 [18 30]]


In [19]:
#4
print(y ** 2)

[[25 36]
 [49 64]]


In [20]:
#5
print ("Dot product between v and w: ", np.dot(v,w))
print ("Dot product between x and v: ", np.dot(x,v))
print ("Dot product between x and y: ", np.dot(x,y))

Dot product between v and w:  219
Dot product between x and v:  [29 77]
Dot product between x and y:  [[19 22]
 [50 58]]


In [23]:
#6
print("x and y along row: \n", np.concatenate((x,y)))
print("\n\nv and w along column: \n", np.concatenate((v,w)))

x and y along row: 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


v and w along column: 
 [ 9 10 11 12]


In [24]:
#7
np.concatenate((x,v))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

We get an error here because x has shape (2,2) while v has shape (2,). Since these arrays have different dimensionality they cannot be concatenated unless both have the same dimensions.

Problem - 4: Matrix Operations:

In [27]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [28]:
#1.1

A_inv = np.linalg.inv(A)
result = A @ A_inv
result = np.round(result).astype(int)

identity = np.eye(2, dtype = int)

print("A * A^-1 =\n", result, "\nI =\n", identity)
if (np.array_equal(result, identity)):
  print("A * A^-1 = I")

A * A^-1 =
 [[1 0]
 [0 1]] 
I =
 [[1 0]
 [0 1]]
A * A^-1 = I


In [29]:
# 1.2

AB = A @ B
BA = B @ A

print("AB =\n", AB, "\n\nBA =\n", BA)
print("\n")
print("A * B = B * A:", np.array_equal(AB, BA))

AB =
 [[23 13]
 [51 29]] 

BA =
 [[36 44]
 [13 16]]


A * B = B * A: False


In [30]:
#1.3

LHS = (A @ B).T
RHS = B.T @ A.T

print("LHS =\n", LHS, "\nRHS =\n", RHS)
if (np.array_equal(LHS, RHS)):
  print("(A.B)T (LHS) = (B)T.(A)T (RHS)")

LHS =
 [[23 51]
 [13 29]] 
RHS =
 [[23 51]
 [13 29]]
(A.B)T (LHS) = (B)T.(A)T (RHS)


In [31]:
# 2

"""
Equations:
2x - 3y + z = -1
 x - y + 2z = -3
3x + y -  z =  9

"""

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]], dtype=float)

B = np.array([-1, -3, 9], dtype=float)

# AX = B
# X = A^-1 . B
# Finding X using np.linalg.inv()

A_inverse = np.linalg.inv(A)
X = A_inverse @ B
print("Using inverse matrix method:\n x = {:.2f}\n y = {:.2f}\n z = {:.2f}".format(X[0], X[1], X[2]))

Using inverse matrix method:
 x = 2.00
 y = 1.00
 z = -2.00


In [32]:
#3

X_solve = np.linalg.solve(A, B)
print("Using np.linalg.sovle():\n x = {:.2f}\n y = {:.2f}\n z = {:.2f}".format(X[0], X[1], X[2]))

Using np.linalg.sovle():
 x = 2.00
 y = 1.00
 z = -2.00


EXPERIMENT:

In [33]:
import time

# python lists
list1 = list(range(1000000))
list2 = list(range(1000000))

# numpy arrays
array1 = np.arange(1000000)
array2 = np.arange(1000000)

In [34]:
# 1

# python lists
start = time.time()
list_add = [list1[i] + list2[i] for i in range(1000000)]
end = time.time()
print("Time for element-wise addition of python lists:", end - start, "s")

# numpy arrays
start = time.time()
array_add = array1 + array2
end = time.time()

print("Time for element-wise addition of numpy arrays:", end - start, "s")

Time for element-wise addition of python lists: 0.17836308479309082 s
Time for element-wise addition of numpy arrays: 0.005465984344482422 s


In [35]:
# 2

# python lists
start = time.time()
list_multiply = [list1[i] * list2[i] for i in range(1000000)]
end = time.time()
print("Time for element-wise multiplication of python lists:", end - start, "s")

# numpy arrays
start = time.time()
array_multiply = array1 * array2
end = time.time()

print("Time for element-wise multiplication of numpy arrays:", end - start, "s")

Time for element-wise multiplication of python lists: 0.15954995155334473 s
Time for element-wise multiplication of numpy arrays: 0.005153179168701172 s


In [36]:
# 3

# python lists
start = time.time()
list_dot = sum(list1[i] * list2[i] for i in range(1000000))
end = time.time()
print("Time for dot-product of python lists:", end - start, end="s\n")

# numpy arrays
start = time.time()
array_dot = np.dot(array1, array2)
end = time.time()

print("Time for dot-product of numpy arrays:", end - start, end="s\n")

Time for dot-product of python lists: 0.16063666343688965s
Time for dot-product of numpy arrays: 0.0017733573913574219s


In [37]:
# 4

# python matrices
python1 = [[1 for _ in range(1000)] for _ in range(1000)]
python2 = [[1 for _ in range(1000)] for _ in range(1000)]
start = time.time()
python3 = [[sum(python1[i][k] * python2[k][j] for k in range(1000))
           for j in range(1000)] for i in range(1000)]
end = time.time()

print("Time for python matrix multiplication:", end - start, "s")

# numpy matrices
np1 = np.ones((1000, 1000))
np2 = np.ones((1000, 1000))

start = time.time()
np3 = np1 @ np2
end = time.time()

print("Time for numpy matrix multiplication:", end - start, "s")

Time for python matrix multiplication: 121.27716112136841 s
Time for numpy matrix multiplication: 0.029270648956298828 s
